// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_Tankopedia_ASP.Data;

#nullable disable

namespace TP_Tankopedia_ASP.Migrations
{
    [DbContext(typeof(TankopediaDbContext))]
    [Migration("20231031174009_usersDataSeed")]
    partial class usersDataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "40e70e4c-4b65-417b-a26f-317a2e99c93e",
                            ConcurrencyStamp = "ddf60701-902e-4fdb-890e-7f954a661bb3",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2c913f9e-1fad-4a08-81ba-505fc006a08e",
                            ConcurrencyStamp = "bde0b98f-a359-4685-b8c9-6393a8df6047",
                            Name = "TankCommander",
                            NormalizedName = "TANKCOMMANDER"
                        },
                        new
                        {
                            Id = "4fb20c39-8ae1-4e27-80f8-01bbb0c311c5",
                            ConcurrencyStamp = "becafbe8-0f2d-468a-83a7-defb9ac7cf18",
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TankUser", b =>
                {
                    b.Property<int>("TanksId")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TanksId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TankUser");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Characteristics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AimingTime")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("AmoCapacity")
                        .HasColumnType("int");

                    b.Property<int>("EnginePower")
                        .HasColumnType("int");

                    b.Property<int>("HullArmor")
                        .HasColumnType("int");

                    b.Property<decimal>("RateOfFire")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("ReloadTime")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<int>("TopSpeed")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("TankId")
                        .IsUnique();

                    b.ToTable("Characteristics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AimingTime = 2m,
                            AmoCapacity = 50,
                            EnginePower = 580,
                            HullArmor = 100,
                            RateOfFire = 9.09m,
                            ReloadTime = 6.60m,
                            TankId = 1,
                            TopSpeed = 50,
                            Weight = 39.80m
                        },
                        new
                        {
                            Id = 2,
                            AimingTime = 2.70m,
                            AmoCapacity = 36,
                            EnginePower = 810,
                            HullArmor = 228,
                            RateOfFire = 7.74m,
                            ReloadTime = 25m,
                            TankId = 2,
                            TopSpeed = 35,
                            Weight = 54.43m
                        },
                        new
                        {
                            Id = 3,
                            AimingTime = 1.70m,
                            AmoCapacity = 60,
                            EnginePower = 830,
                            HullArmor = 70,
                            RateOfFire = 6.45m,
                            ReloadTime = 9.30m,
                            TankId = 3,
                            TopSpeed = 70,
                            Weight = 42m
                        },
                        new
                        {
                            Id = 4,
                            AimingTime = 2.50m,
                            AmoCapacity = 30,
                            EnginePower = 550,
                            HullArmor = 200,
                            RateOfFire = 4.46m,
                            ReloadTime = 13.45m,
                            TankId = 4,
                            TopSpeed = 35,
                            Weight = 49.59m
                        },
                        new
                        {
                            Id = 5,
                            AimingTime = 4.50m,
                            AmoCapacity = 36,
                            EnginePower = 720,
                            HullArmor = 16,
                            RateOfFire = 2.50m,
                            ReloadTime = 52m,
                            TankId = 5,
                            TopSpeed = 62,
                            Weight = 38m
                        },
                        new
                        {
                            Id = 6,
                            AimingTime = 1.90m,
                            AmoCapacity = 20,
                            EnginePower = 530,
                            HullArmor = 50,
                            RateOfFire = 4.29m,
                            ReloadTime = 14m,
                            TankId = 6,
                            TopSpeed = 68,
                            Weight = 12.40m
                        },
                        new
                        {
                            Id = 7,
                            AimingTime = 3.20m,
                            AmoCapacity = 100,
                            EnginePower = 1060,
                            HullArmor = 150,
                            RateOfFire = 5.10m,
                            ReloadTime = 12m,
                            TankId = 7,
                            TopSpeed = 29,
                            Weight = 150.36m
                        },
                        new
                        {
                            Id = 8,
                            AimingTime = 2.10m,
                            AmoCapacity = 44,
                            EnginePower = 700,
                            HullArmor = 130,
                            RateOfFire = 6.67m,
                            ReloadTime = 9m,
                            TankId = 8,
                            TopSpeed = 50,
                            Weight = 50.98m
                        },
                        new
                        {
                            Id = 9,
                            AimingTime = 1.10m,
                            AmoCapacity = 50,
                            EnginePower = 730,
                            HullArmor = 40,
                            RateOfFire = 8.57m,
                            ReloadTime = 7m,
                            TankId = 9,
                            TopSpeed = 50,
                            Weight = 40.30m
                        },
                        new
                        {
                            Id = 10,
                            AimingTime = 2.30m,
                            AmoCapacity = 35,
                            EnginePower = 900,
                            HullArmor = 80,
                            RateOfFire = 4.14m,
                            ReloadTime = 14.50m,
                            TankId = 10,
                            TopSpeed = 40,
                            Weight = 56.10m
                        },
                        new
                        {
                            Id = 11,
                            AimingTime = 2.50m,
                            AmoCapacity = 35,
                            EnginePower = 750,
                            HullArmor = 40,
                            RateOfFire = 4.32m,
                            ReloadTime = 10.00m,
                            TankId = 11,
                            TopSpeed = 65,
                            Weight = 40.10m
                        },
                        new
                        {
                            Id = 12,
                            AimingTime = 1.60m,
                            AmoCapacity = 43,
                            EnginePower = 500,
                            HullArmor = 40,
                            RateOfFire = 7.50m,
                            ReloadTime = 8.00m,
                            TankId = 12,
                            TopSpeed = 83,
                            Weight = 14.83m
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Nation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("pictureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("pictureId");

                    b.ToTable("Nations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "U.S.A.",
                            pictureId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "U.S.S.R",
                            pictureId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany",
                            pictureId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "China",
                            pictureId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "France",
                            pictureId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "U.K.",
                            pictureId = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Japan",
                            pictureId = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "Czechoslovakia",
                            pictureId = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sweden",
                            pictureId = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "Poland",
                            pictureId = 10
                        },
                        new
                        {
                            Id = 11,
                            Name = "Italy",
                            pictureId = 11
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Picture", b =>
                {
                    b.Property<int>("pictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pictureId"), 1L, 1);

                    b.Property<DateTime>("DateOfAddition")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pictureId");

                    b.ToTable("Picture");

                    b.HasData(
                        new
                        {
                            pictureId = 1,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9934),
                            FileName = "9bdcc69e-9b0a-4aaf-b79a-8c8e5537f4b5.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 2,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9968),
                            FileName = "984bf917-4720-4011-8d12-854f1015a33f.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 3,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9971),
                            FileName = "253a6bfd-ccbb-4296-bff3-b655b6599ebd.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 4,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9973),
                            FileName = "8737e698-b5da-4aef-b0dc-55d8eccaf61d.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 5,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9976),
                            FileName = "7a1e115a-b107-4637-b2c0-1e1a86ffed7d.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 6,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9978),
                            FileName = "fe0afbdf-9fb4-4fd8-b09a-7977dbd77bc0.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 7,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9980),
                            FileName = "00c84d4d-a645-44f2-8b1a-eabf0e3c62d4.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 8,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9983),
                            FileName = "c5d1102f-34bd-46a0-9e6a-ab2544cb9621.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 9,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9985),
                            FileName = "b360c5ac-dc5e-4310-a833-15a0af7a1929.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 10,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9988),
                            FileName = "5a428329-03db-458b-b882-5192fbd9ebe9.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 11,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9990),
                            FileName = "8876fef9-7f61-4f1b-b2ed-aa1c03a7eb23.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 12,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9992),
                            FileName = "0cdd4032-0352-4254-9161-5d8f5fc33287.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 13,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9994),
                            FileName = "b6f2b7c6-1914-4ecf-8271-791089c22b1c.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 14,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9996),
                            FileName = "0a66050b-617b-426d-8d01-1cfdc53f6a9c.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 15,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 817, DateTimeKind.Local).AddTicks(9999),
                            FileName = "9e04a735-2cdf-4151-81aa-f9319e5ab21a.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 16,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 818, DateTimeKind.Local).AddTicks(1),
                            FileName = "f90f830b-0acb-4ae3-8bfe-aee7622be9a5.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 17,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 818, DateTimeKind.Local).AddTicks(3),
                            FileName = "333249ff-b0a1-479b-a988-89caa173e1dc.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 18,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 818, DateTimeKind.Local).AddTicks(6),
                            FileName = "564e8122-f919-4b3e-a248-c5f572be4b60.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 19,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 818, DateTimeKind.Local).AddTicks(8),
                            FileName = "5ff17622-d961-432c-be99-66a58024a72f.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 20,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 818, DateTimeKind.Local).AddTicks(10),
                            FileName = "c721c906-08a7-4f73-af0d-fbf4984ad193.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 21,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 818, DateTimeKind.Local).AddTicks(12),
                            FileName = "4136038d-1213-4646-8d74-4bd152fa0e93.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 22,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 818, DateTimeKind.Local).AddTicks(14),
                            FileName = "590fbeff-440c-44c7-ac82-cdd8b879be67.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            pictureId = 23,
                            DateOfAddition = new DateTime(2023, 10, 31, 13, 40, 8, 818, DateTimeKind.Local).AddTicks(17),
                            FileName = "152499c3-41c5-460f-92e0-330b4462895e.png",
                            MimeType = "image/png"
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.StrategicRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("imageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StrategicRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Versatile Light Tanks"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wheeled Light Tanks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Assault Medium Tanks"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Versatile Medium Tanks"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sniper Medium Tanks"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Support Medium Tanks"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Assault Heavy Tanks"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Versatile Heavy Tanks"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Breakthrough Heavy Tanks"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Support Heavy Tanks"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Assault Tank Destroyers"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Versatile Tank Destroyers"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sniper Tank Destroyers"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Support Tank Destroyer"
                        },
                        new
                        {
                            Id = 15,
                            Name = "SPGs"
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("NationID")
                        .HasColumnType("int");

                    b.Property<int>("StrategicRoleId")
                        .HasColumnType("int");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.Property<int?>("YearOfCreation")
                        .HasColumnType("int");

                    b.Property<int?>("pictureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationID");

                    b.HasIndex("StrategicRoleId");

                    b.HasIndex("TypeID");

                    b.HasIndex("pictureId");

                    b.ToTable("Tanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Development of the first Soviet post-war medium tank started in 1951. In 1961, the T-62 tank with a smoothbore gun was deployed. At the same time a variant, the T-62A, with a rifled gun was also deployed. In March 1962, mass production of the T-62A was discontinued. The T-62 tank was mass-produced from 1961 through 1975, with a total of twenty thousand vehicles manufactured. Later modifications of the vehicle are still in service.",
                            Name = "T-62A",
                            NationID = 2,
                            StrategicRoleId = 4,
                            TypeID = 2,
                            YearOfCreation = 1961,
                            pictureId = 12
                        },
                        new
                        {
                            Id = 2,
                            Description = "A project for a heavy tank with an oscillating turret and automatic loader, developed from 1951. Experimental turrets for 120 mm and 155 mm guns were manufactured by 1957. However, the project was deemed unsuccessful and development was discontinued.",
                            Name = "T57 HEAVY TANK",
                            NationID = 1,
                            StrategicRoleId = 10,
                            TypeID = 3,
                            YearOfCreation = 1957,
                            pictureId = 13
                        },
                        new
                        {
                            Id = 3,
                            Description = "Main battle tank of the Federal Republic of Germany. Development was started in 1956. The first prototypes were built in 1965 at the Krauss-Maffei factory. The Leopard 1 saw service in the armies of more than 10 countries.",
                            Name = "LEOPARD 1",
                            NationID = 3,
                            StrategicRoleId = 5,
                            TypeID = 2,
                            YearOfCreation = 1965,
                            pictureId = 14
                        },
                        new
                        {
                            Id = 4,
                            Description = "A self-propelled gun developed on the basis of the WZ-111 heavy tank in the first half of the 1960s. The development of the WZ-111 was discontinued, and all activity on the vehicle was canceled. No prototypes were built.",
                            Name = "WZ-111G FT",
                            NationID = 4,
                            StrategicRoleId = 12,
                            TypeID = 4,
                            YearOfCreation = 1960,
                            pictureId = 15
                        },
                        new
                        {
                            Id = 5,
                            Description = "An experimental project for an SPG that used some elements of the U.S. M47 chassis. As compared to the Bat.-Châtillon 155 55, the vehicle had a different turret and featured the magazine loading system. Existed only in blueprints.",
                            Name = "BAT.-CHÂTILLON 155 58",
                            NationID = 5,
                            StrategicRoleId = 15,
                            TypeID = 5,
                            YearOfCreation = 1960,
                            pictureId = 16
                        },
                        new
                        {
                            Id = 6,
                            Description = "A light tank project with an oscillating turret for providing anti-tank defense behind infantry positions. No prototypes were built, and it existed only in blueprints.",
                            Name = "MANTICORE ",
                            NationID = 6,
                            StrategicRoleId = 1,
                            TypeID = 1,
                            pictureId = 17
                        },
                        new
                        {
                            Id = 7,
                            Description = "Development of the superheavy tank was started after the Battles of Khalkhyn Gol in 1939. The vehicle was designed as a maneuverable fire unit that was unprecedented in scale—its hull alone weighed 100 tons. Only one prototype was built, without a turret and made of construction steel. Trials were discontinued due to the unreliable engine; at the end of 1944, the prototype was scrapped. The 15 cm howitzer was to be mounted on the tank after its assembly.",
                            Name = "O-I ",
                            NationID = 7,
                            StrategicRoleId = 7,
                            TypeID = 3,
                            YearOfCreation = 1939,
                            pictureId = 18
                        },
                        new
                        {
                            Id = 8,
                            Description = "In the early 1950s, the ČKD company developed a project of a heavy tank for the Czechoslovakian Army based on concepts of the Soviet and German tank-building schools combined with its own ideas. The project was discontinued due to the unification of armament of Warsaw Pact countries. No prototypes were ever built.",
                            Name = "TNH T VZ. 51",
                            NationID = 8,
                            StrategicRoleId = 9,
                            TypeID = 3,
                            YearOfCreation = 1950,
                            pictureId = 19
                        },
                        new
                        {
                            Id = 9,
                            Description = "Developed from 1969 through 1971 as a modernization of the Strv 103. Unlike the previous Strv 103A version, the Strv 103B was equipped with a more powerful gas-turbine engine, laser rangefinder, and infrared devices. The vehicle also accommodated the mounting of amphibious add-on equipment. In 1970, 220 vehicles went into service. At the same time, the vehicles of the previous modification were converted to the Strv 103B, which resulted in a total of 290 vehicles by 1971.",
                            Name = "STRV 103B",
                            NationID = 9,
                            StrategicRoleId = 13,
                            TypeID = 4,
                            YearOfCreation = 1971,
                            pictureId = 20
                        },
                        new
                        {
                            Id = 10,
                            Description = "The vehicle was developed in the 1950s. Using the scaling method, Polish engineers took the elements of a medium tank chassis as the base and adjusted those elements to a different weight category. They were guided by the Soviet T-54, which meant that some of the vehicle's components were similar to the first versions of the Soviet medium tank. As a result, it was an extremely interesting design with a rather low silhouette. However, it existed only in blueprints. Such a heavy vehicle would require too many resources of the Polish industry.",
                            Name = "56TP",
                            NationID = 10,
                            StrategicRoleId = 8,
                            TypeID = 3,
                            YearOfCreation = 1950,
                            pictureId = 21
                        },
                        new
                        {
                            Id = 11,
                            Description = "In 1969, the Italian military delegation visited Germany to discuss the purchase of Leopard tanks. However, not all members of the delegation agreed with the acquisition of foreign vehicles. The Italian military experts and engineers specified the main requirements for the future tank: the slope angle of armor plates, the cast turret and gun mantlet, as well as the powerful engine from Mitsubishi that allowed production of a small, light, maneuverable, but perfectly-armored vehicle. The British and Soviet design plans collected by SIFAR-SID were taken into account. Development of the project was discontinued at the drafting and modelling stage.",
                            Name = "PROGETTO M40 MOD. 65",
                            NationID = 11,
                            StrategicRoleId = 6,
                            TypeID = 2,
                            pictureId = 22
                        },
                        new
                        {
                            Id = 12,
                            Description = "In the early 1960s, the 75 mm caliber guns were deemed outdated. During 1963 and 1964, a total of 650 vehicles with FL 11 turrets were re-equipped with 90 mm guns to improve their firepower. The other vehicles with the same turret and \"outdated\" guns were removed from service in the French Army.",
                            Name = "PANHARD EBR 90",
                            NationID = 5,
                            StrategicRoleId = 2,
                            TypeID = 1,
                            YearOfCreation = 1964,
                            pictureId = 23
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.TankModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<string>("TypeModule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("TankModules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-62A",
                            TankId = 1,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 2,
                            Name = "V-55",
                            TankId = 1,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 3,
                            Name = "R-123",
                            TankId = 1,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 4,
                            Name = "T-62A",
                            TankId = 1,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 5,
                            Name = "100 MM U-8TS",
                            TankId = 1,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 6,
                            Name = "T97",
                            TankId = 2,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CONTINENTAL AV-1790-5C",
                            TankId = 2,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 8,
                            Name = "AN/VRC-3",
                            TankId = 2,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 9,
                            Name = "T169",
                            TankId = 2,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 10,
                            Name = "120 MM GUN T179",
                            TankId = 2,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 11,
                            Name = "LEOPARD 1",
                            TankId = 3,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 12,
                            Name = "MTU MB 838 CAM 500A",
                            TankId = 3,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 13,
                            Name = "SEM 25A",
                            TankId = 3,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 14,
                            Name = "LEOPARD 1",
                            TankId = 3,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 15,
                            Name = "10,5CM BORDKANONE L7A3",
                            TankId = 3,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 16,
                            Name = "WZ-111G FT MODEL 4",
                            TankId = 4,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 17,
                            Name = "12150LTG",
                            TankId = 4,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 18,
                            Name = "A-220A",
                            TankId = 4,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 19,
                            Name = "152 MM 59-152JG FT",
                            TankId = 4,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 20,
                            Name = "BatingnollesChatillon 155",
                            TankId = 5,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 21,
                            Name = "HISPANO-SUIZA HS 110",
                            TankId = 5,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 22,
                            Name = "SCR 528F",
                            TankId = 5,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 23,
                            Name = "CANON DE 155 MM",
                            TankId = 5,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 24,
                            Name = "MANTICORE 1955",
                            TankId = 6,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 25,
                            Name = "ROLL-ROYCE B81",
                            TankId = 6,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 26,
                            Name = "C42 VHF",
                            TankId = 6,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 27,
                            Name = "MANTICORE 1955",
                            TankId = 6,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 28,
                            Name = "QF 105 MM GUN",
                            TankId = 6,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 29,
                            Name = "O-I KAI",
                            TankId = 7,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 30,
                            Name = "2X KAWASAKI TYPE 98 V-12",
                            TankId = 7,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 31,
                            Name = "TYPE 94 MK.4 BO",
                            TankId = 7,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 32,
                            Name = "O-I",
                            TankId = 7,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 33,
                            Name = "15 CM HOWITZER TYPE 96",
                            TankId = 7,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 34,
                            Name = "TNH T VZ 51 DRUHY",
                            TankId = 8,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 35,
                            Name = "CKD AXK2",
                            TankId = 8,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 36,
                            Name = "RADIOSTANICE RM-31T",
                            TankId = 8,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 37,
                            Name = "TNH T VZ 61 PRVNI",
                            TankId = 8,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 38,
                            Name = "122 MM VZ 44-51 2A",
                            TankId = 8,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 39,
                            Name = "STRV 103B",
                            TankId = 9,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 40,
                            Name = "MOTORAGGREGAT 9",
                            TankId = 9,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 41,
                            Name = "RA 421",
                            TankId = 9,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 42,
                            Name = "10.5 CM KAN STRV 103 L/62",
                            TankId = 9,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 43,
                            Name = "56TP",
                            TankId = 10,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 44,
                            Name = "W12-5P-1",
                            TankId = 10,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 45,
                            Name = "10RT-26PA",
                            TankId = 10,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 46,
                            Name = "56TP",
                            TankId = 10,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 47,
                            Name = "122 MM ARMATA WZ.56",
                            TankId = 10,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 48,
                            Name = "PROGETTO M40 MOD.65",
                            TankId = 11,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 49,
                            Name = "MITSUBISHI 10ZF",
                            TankId = 11,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 50,
                            Name = "R 19",
                            TankId = 11,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 51,
                            Name = "PROGETTO M40 MOD.65",
                            TankId = 11,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 52,
                            Name = "CANNONE DA 105/51 M68",
                            TankId = 11,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 53,
                            Name = "PANGARD EBR 90",
                            TankId = 12,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 54,
                            Name = "PANHARD H-101",
                            TankId = 12,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 55,
                            Name = "SCR 508",
                            TankId = 12,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 56,
                            Name = "PANHARD EBR 90",
                            TankId = 12,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 57,
                            Name = "90 MM CN 90 F3",
                            TankId = 12,
                            TypeModule = "Gun"
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.TypeTank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("imageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeTanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Light Tank"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium Tank"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Heavy Tank"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tank Destroyer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SPGS"
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a3b02db3-a70c-4cad-8940-84bb4b37ed30",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "068c48f0-b03a-4826-bcbf-a1662780071a",
                            Email = "admin@tankopedia.ca",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@TANKOPEDIA.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAECPrXqnmTU6XvqZn3Z6M709VEC337RPK3oaE+LTY8pKXvlRL18bz9YT8Y9frICigug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c00c401c-e006-4b18-8c87-e4723e475311",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "5ee110b5-3ca6-462f-8bde-886d1c6e827d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b45a4044-29dd-422c-af6b-351759e086d5",
                            Email = "commander@tankopedia.ca",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "COMMANDER@TANKOPEDIA.COM",
                            NormalizedUserName = "COMMANDER",
                            PasswordHash = "AQAAAAEAACcQAAAAEI+IWdzBrr21AXgRyBvUofrW+MXq2soMRvOFtoFR8nIS4jzUy/IqJFq2sLQaX+w6Rw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "92224d65-000e-4f96-85a3-4b0c0fec5abd",
                            TwoFactorEnabled = false,
                            UserName = "Commander"
                        },
                        new
                        {
                            Id = "f6c880eb-13ba-49c7-a763-79f9d3bff5b1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "89888b5b-75ec-4fae-9526-a27b9a578a19",
                            Email = "visitor@tankopedia.ca",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VISITOR@TANKOPEDIA.COM",
                            NormalizedUserName = "VISITOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ5/Qafq4hy3nbN/Us4I9Kc/P8P4lzDBn/5Gqrohr/UsgpyD0L23ioWPaWKqnkFOZw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7aee4da-6033-4f2a-a0d7-8667f052c260",
                            TwoFactorEnabled = false,
                            UserName = "Visitor"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP_Tankopedia_ASP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankUser", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.Tank", null)
                        .WithMany()
                        .HasForeignKey("TanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP_Tankopedia_ASP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Characteristics", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.Tank", "Tank")
                        .WithOne("Characteristics")
                        .HasForeignKey("TP_Tankopedia_ASP.Models.Characteristics", "TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Nation", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("pictureId");

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Tank", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.Nation", "Nation")
                        .WithMany("Tanks")
                        .HasForeignKey("NationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP_Tankopedia_ASP.Models.StrategicRole", "StrategicRole")
                        .WithMany("Tanks")
                        .HasForeignKey("StrategicRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP_Tankopedia_ASP.Models.TypeTank", "TypeTank")
                        .WithMany("Tanks")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP_Tankopedia_ASP.Models.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("pictureId");

                    b.Navigation("Nation");

                    b.Navigation("Picture");

                    b.Navigation("StrategicRole");

                    b.Navigation("TypeTank");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.TankModule", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.Tank", "Tank")
                        .WithMany("TankModules")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Nation", b =>
                {
                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.StrategicRole", b =>
                {
                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Tank", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("TankModules");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.TypeTank", b =>
                {
                    b.Navigation("Tanks");
                });
#pragma warning restore 612, 618
        }
    }
}
