// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_Tankopedia_ASP.Data;

#nullable disable

namespace TP_Tankopedia_ASP.Migrations
{
    [DbContext(typeof(TankopediaDbContext))]
    partial class TankopediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Characteristics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AimingTime")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("AmoCapacity")
                        .HasColumnType("int");

                    b.Property<int>("EnginePower")
                        .HasColumnType("int");

                    b.Property<int>("HullArmor")
                        .HasColumnType("int");

                    b.Property<decimal>("RateOfFire")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("ReloadTime")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<int>("TopSpeed")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("TankId")
                        .IsUnique();

                    b.ToTable("Characteristics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AimingTime = 2m,
                            AmoCapacity = 50,
                            EnginePower = 580,
                            HullArmor = 100,
                            RateOfFire = 9.09m,
                            ReloadTime = 6.60m,
                            TankId = 1,
                            TopSpeed = 50,
                            Weight = 39.80m
                        },
                        new
                        {
                            Id = 2,
                            AimingTime = 2.70m,
                            AmoCapacity = 36,
                            EnginePower = 810,
                            HullArmor = 228,
                            RateOfFire = 7.74m,
                            ReloadTime = 25m,
                            TankId = 2,
                            TopSpeed = 35,
                            Weight = 54.43m
                        },
                        new
                        {
                            Id = 3,
                            AimingTime = 1.70m,
                            AmoCapacity = 60,
                            EnginePower = 830,
                            HullArmor = 70,
                            RateOfFire = 6.45m,
                            ReloadTime = 9.30m,
                            TankId = 3,
                            TopSpeed = 70,
                            Weight = 42m
                        },
                        new
                        {
                            Id = 4,
                            AimingTime = 2.50m,
                            AmoCapacity = 30,
                            EnginePower = 550,
                            HullArmor = 200,
                            RateOfFire = 4.46m,
                            ReloadTime = 13.45m,
                            TankId = 4,
                            TopSpeed = 35,
                            Weight = 49.59m
                        },
                        new
                        {
                            Id = 5,
                            AimingTime = 4.50m,
                            AmoCapacity = 36,
                            EnginePower = 720,
                            HullArmor = 16,
                            RateOfFire = 2.50m,
                            ReloadTime = 52m,
                            TankId = 5,
                            TopSpeed = 62,
                            Weight = 38m
                        },
                        new
                        {
                            Id = 6,
                            AimingTime = 1.90m,
                            AmoCapacity = 20,
                            EnginePower = 530,
                            HullArmor = 50,
                            RateOfFire = 4.29m,
                            ReloadTime = 14m,
                            TankId = 6,
                            TopSpeed = 68,
                            Weight = 12.40m
                        },
                        new
                        {
                            Id = 7,
                            AimingTime = 3.20m,
                            AmoCapacity = 100,
                            EnginePower = 1060,
                            HullArmor = 150,
                            RateOfFire = 5.10m,
                            ReloadTime = 12m,
                            TankId = 7,
                            TopSpeed = 29,
                            Weight = 150.36m
                        },
                        new
                        {
                            Id = 8,
                            AimingTime = 2.10m,
                            AmoCapacity = 44,
                            EnginePower = 700,
                            HullArmor = 130,
                            RateOfFire = 6.67m,
                            ReloadTime = 9m,
                            TankId = 8,
                            TopSpeed = 50,
                            Weight = 50.98m
                        },
                        new
                        {
                            Id = 9,
                            AimingTime = 1.10m,
                            AmoCapacity = 50,
                            EnginePower = 730,
                            HullArmor = 40,
                            RateOfFire = 8.57m,
                            ReloadTime = 7m,
                            TankId = 9,
                            TopSpeed = 50,
                            Weight = 40.30m
                        },
                        new
                        {
                            Id = 10,
                            AimingTime = 2.30m,
                            AmoCapacity = 35,
                            EnginePower = 900,
                            HullArmor = 80,
                            RateOfFire = 4.14m,
                            ReloadTime = 14.50m,
                            TankId = 10,
                            TopSpeed = 40,
                            Weight = 56.10m
                        },
                        new
                        {
                            Id = 11,
                            AimingTime = 2.50m,
                            AmoCapacity = 35,
                            EnginePower = 750,
                            HullArmor = 40,
                            RateOfFire = 4.32m,
                            ReloadTime = 10.00m,
                            TankId = 11,
                            TopSpeed = 65,
                            Weight = 40.10m
                        },
                        new
                        {
                            Id = 12,
                            AimingTime = 1.60m,
                            AmoCapacity = 43,
                            EnginePower = 500,
                            HullArmor = 40,
                            RateOfFire = 7.50m,
                            ReloadTime = 8.00m,
                            TankId = 12,
                            TopSpeed = 83,
                            Weight = 14.83m
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Nation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Nations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "U.S.A."
                        },
                        new
                        {
                            Id = 2,
                            Name = "U.S.S.R"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 4,
                            Name = "China"
                        },
                        new
                        {
                            Id = 5,
                            Name = "France"
                        },
                        new
                        {
                            Id = 6,
                            Name = "U.K."
                        },
                        new
                        {
                            Id = 7,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Czechoslovakia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Italy"
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.StrategicRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("imageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StrategicRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Versatile Light Tanks"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wheeled Light Tanks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Assault Medium Tanks"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Versatile Medium Tanks"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sniper Medium Tanks"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Support Medium Tanks"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Assault Heavy Tanks"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Versatile Heavy Tanks"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Breakthrough Heavy Tanks"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Support Heavy Tanks"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Assault Tank Destroyers"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Versatile Tank Destroyers"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sniper Tank Destroyers"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Support Tank Destroyer"
                        },
                        new
                        {
                            Id = 15,
                            Name = "SPGs"
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("NationID")
                        .HasColumnType("int");

                    b.Property<int>("StrategicRoleId")
                        .HasColumnType("int");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.Property<int?>("YearOfCreation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationID");

                    b.HasIndex("StrategicRoleId");

                    b.HasIndex("TypeID");

                    b.ToTable("Tanks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Development of the first Soviet post-war medium tank started in 1951. In 1961, the T-62 tank with a smoothbore gun was deployed. At the same time a variant, the T-62A, with a rifled gun was also deployed. In March 1962, mass production of the T-62A was discontinued. The T-62 tank was mass-produced from 1961 through 1975, with a total of twenty thousand vehicles manufactured. Later modifications of the vehicle are still in service.",
                            Name = "T-62A",
                            NationID = 2,
                            StrategicRoleId = 4,
                            TypeID = 2,
                            YearOfCreation = 1961
                        },
                        new
                        {
                            Id = 2,
                            Description = "A project for a heavy tank with an oscillating turret and automatic loader, developed from 1951. Experimental turrets for 120 mm and 155 mm guns were manufactured by 1957. However, the project was deemed unsuccessful and development was discontinued.",
                            Name = "T57 HEAVY TANK",
                            NationID = 1,
                            StrategicRoleId = 10,
                            TypeID = 3,
                            YearOfCreation = 1957
                        },
                        new
                        {
                            Id = 3,
                            Description = "Main battle tank of the Federal Republic of Germany. Development was started in 1956. The first prototypes were built in 1965 at the Krauss-Maffei factory. The Leopard 1 saw service in the armies of more than 10 countries.",
                            Name = "LEOPARD 1",
                            NationID = 3,
                            StrategicRoleId = 5,
                            TypeID = 2,
                            YearOfCreation = 1965
                        },
                        new
                        {
                            Id = 4,
                            Description = "A self-propelled gun developed on the basis of the WZ-111 heavy tank in the first half of the 1960s. The development of the WZ-111 was discontinued, and all activity on the vehicle was canceled. No prototypes were built.",
                            Name = "WZ-111G FT",
                            NationID = 4,
                            StrategicRoleId = 12,
                            TypeID = 4,
                            YearOfCreation = 1960
                        },
                        new
                        {
                            Id = 5,
                            Description = "An experimental project for an SPG that used some elements of the U.S. M47 chassis. As compared to the Bat.-Châtillon 155 55, the vehicle had a different turret and featured the magazine loading system. Existed only in blueprints.",
                            Name = "BAT.-CHÂTILLON 155 58",
                            NationID = 5,
                            StrategicRoleId = 15,
                            TypeID = 5,
                            YearOfCreation = 1960
                        },
                        new
                        {
                            Id = 6,
                            Description = "A light tank project with an oscillating turret for providing anti-tank defense behind infantry positions. No prototypes were built, and it existed only in blueprints.",
                            Name = "MANTICORE ",
                            NationID = 6,
                            StrategicRoleId = 1,
                            TypeID = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Development of the superheavy tank was started after the Battles of Khalkhyn Gol in 1939. The vehicle was designed as a maneuverable fire unit that was unprecedented in scale—its hull alone weighed 100 tons. Only one prototype was built, without a turret and made of construction steel. Trials were discontinued due to the unreliable engine; at the end of 1944, the prototype was scrapped. The 15 cm howitzer was to be mounted on the tank after its assembly.",
                            Name = "O-I ",
                            NationID = 7,
                            StrategicRoleId = 7,
                            TypeID = 3,
                            YearOfCreation = 1939
                        },
                        new
                        {
                            Id = 8,
                            Description = "In the early 1950s, the ČKD company developed a project of a heavy tank for the Czechoslovakian Army based on concepts of the Soviet and German tank-building schools combined with its own ideas. The project was discontinued due to the unification of armament of Warsaw Pact countries. No prototypes were ever built.",
                            Name = "TNH T VZ. 51",
                            NationID = 8,
                            StrategicRoleId = 9,
                            TypeID = 3,
                            YearOfCreation = 1950
                        },
                        new
                        {
                            Id = 9,
                            Description = "Developed from 1969 through 1971 as a modernization of the Strv 103. Unlike the previous Strv 103A version, the Strv 103B was equipped with a more powerful gas-turbine engine, laser rangefinder, and infrared devices. The vehicle also accommodated the mounting of amphibious add-on equipment. In 1970, 220 vehicles went into service. At the same time, the vehicles of the previous modification were converted to the Strv 103B, which resulted in a total of 290 vehicles by 1971.",
                            Name = "STRV 103B",
                            NationID = 9,
                            StrategicRoleId = 13,
                            TypeID = 4,
                            YearOfCreation = 1971
                        },
                        new
                        {
                            Id = 10,
                            Description = "The vehicle was developed in the 1950s. Using the scaling method, Polish engineers took the elements of a medium tank chassis as the base and adjusted those elements to a different weight category. They were guided by the Soviet T-54, which meant that some of the vehicle's components were similar to the first versions of the Soviet medium tank. As a result, it was an extremely interesting design with a rather low silhouette. However, it existed only in blueprints. Such a heavy vehicle would require too many resources of the Polish industry.",
                            Name = "56TP",
                            NationID = 10,
                            StrategicRoleId = 8,
                            TypeID = 3,
                            YearOfCreation = 1950
                        },
                        new
                        {
                            Id = 11,
                            Description = "In 1969, the Italian military delegation visited Germany to discuss the purchase of Leopard tanks. However, not all members of the delegation agreed with the acquisition of foreign vehicles. The Italian military experts and engineers specified the main requirements for the future tank: the slope angle of armor plates, the cast turret and gun mantlet, as well as the powerful engine from Mitsubishi that allowed production of a small, light, maneuverable, but perfectly-armored vehicle. The British and Soviet design plans collected by SIFAR-SID were taken into account. Development of the project was discontinued at the drafting and modelling stage.",
                            Name = "PROGETTO M40 MOD. 65",
                            NationID = 11,
                            StrategicRoleId = 6,
                            TypeID = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "In the early 1960s, the 75 mm caliber guns were deemed outdated. During 1963 and 1964, a total of 650 vehicles with FL 11 turrets were re-equipped with 90 mm guns to improve their firepower. The other vehicles with the same turret and \"outdated\" guns were removed from service in the French Army.",
                            Name = "PANHARD EBR 90",
                            NationID = 5,
                            StrategicRoleId = 2,
                            TypeID = 1,
                            YearOfCreation = 1964
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.TankModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<string>("TypeModule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("TankModules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-62A",
                            TankId = 1,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 2,
                            Name = "V-55",
                            TankId = 1,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 3,
                            Name = "R-123",
                            TankId = 1,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 4,
                            Name = "T-62A",
                            TankId = 1,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 5,
                            Name = "100 MM U-8TS",
                            TankId = 1,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 6,
                            Name = "T97",
                            TankId = 2,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CONTINENTAL AV-1790-5C",
                            TankId = 2,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 8,
                            Name = "AN/VRC-3",
                            TankId = 2,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 9,
                            Name = "T169",
                            TankId = 2,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 10,
                            Name = "120 MM GUN T179",
                            TankId = 2,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 11,
                            Name = "LEOPARD 1",
                            TankId = 3,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 12,
                            Name = "MTU MB 838 CAM 500A",
                            TankId = 3,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 13,
                            Name = "SEM 25A",
                            TankId = 3,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 14,
                            Name = "LEOPARD 1",
                            TankId = 3,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 15,
                            Name = "10,5CM BORDKANONE L7A3",
                            TankId = 3,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 16,
                            Name = "WZ-111G FT MODEL 4",
                            TankId = 4,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 17,
                            Name = "12150LTG",
                            TankId = 4,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 18,
                            Name = "A-220A",
                            TankId = 4,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 19,
                            Name = "152 MM 59-152JG FT",
                            TankId = 4,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 20,
                            Name = "BatingnollesChatillon 155",
                            TankId = 5,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 21,
                            Name = "HISPANO-SUIZA HS 110",
                            TankId = 5,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 22,
                            Name = "SCR 528F",
                            TankId = 5,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 23,
                            Name = "CANON DE 155 MM",
                            TankId = 5,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 24,
                            Name = "MANTICORE 1955",
                            TankId = 6,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 25,
                            Name = "ROLL-ROYCE B81",
                            TankId = 6,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 26,
                            Name = "C42 VHF",
                            TankId = 6,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 27,
                            Name = "MANTICORE 1955",
                            TankId = 6,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 28,
                            Name = "QF 105 MM GUN",
                            TankId = 6,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 29,
                            Name = "O-I KAI",
                            TankId = 7,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 30,
                            Name = "2X KAWASAKI TYPE 98 V-12",
                            TankId = 7,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 31,
                            Name = "TYPE 94 MK.4 BO",
                            TankId = 7,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 32,
                            Name = "O-I",
                            TankId = 7,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 33,
                            Name = "15 CM HOWITZER TYPE 96",
                            TankId = 7,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 34,
                            Name = "TNH T VZ 51 DRUHY",
                            TankId = 8,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 35,
                            Name = "CKD AXK2",
                            TankId = 8,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 36,
                            Name = "RADIOSTANICE RM-31T",
                            TankId = 8,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 37,
                            Name = "TNH T VZ 61 PRVNI",
                            TankId = 8,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 38,
                            Name = "122 MM VZ 44-51 2A",
                            TankId = 8,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 39,
                            Name = "STRV 103B",
                            TankId = 9,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 40,
                            Name = "MOTORAGGREGAT 9",
                            TankId = 9,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 41,
                            Name = "RA 421",
                            TankId = 9,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 42,
                            Name = "10.5 CM KAN STRV 103 L/62",
                            TankId = 9,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 43,
                            Name = "56TP",
                            TankId = 10,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 44,
                            Name = "W12-5P-1",
                            TankId = 10,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 45,
                            Name = "10RT-26PA",
                            TankId = 10,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 46,
                            Name = "56TP",
                            TankId = 10,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 47,
                            Name = "122 MM ARMATA WZ.56",
                            TankId = 10,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 48,
                            Name = "PROGETTO M40 MOD.65",
                            TankId = 11,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 49,
                            Name = "MITSUBISHI 10ZF",
                            TankId = 11,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 50,
                            Name = "R 19",
                            TankId = 11,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 51,
                            Name = "PROGETTO M40 MOD.65",
                            TankId = 11,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 52,
                            Name = "CANNONE DA 105/51 M68",
                            TankId = 11,
                            TypeModule = "Gun"
                        },
                        new
                        {
                            Id = 53,
                            Name = "PANGARD EBR 90",
                            TankId = 12,
                            TypeModule = "Chassis"
                        },
                        new
                        {
                            Id = 54,
                            Name = "PANHARD H-101",
                            TankId = 12,
                            TypeModule = "Engine"
                        },
                        new
                        {
                            Id = 55,
                            Name = "SCR 508",
                            TankId = 12,
                            TypeModule = "Radio"
                        },
                        new
                        {
                            Id = 56,
                            Name = "PANHARD EBR 90",
                            TankId = 12,
                            TypeModule = "Turret"
                        },
                        new
                        {
                            Id = 57,
                            Name = "90 MM CN 90 F3",
                            TankId = 12,
                            TypeModule = "Gun"
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.TypeTank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("imageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeTanks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Light Tank"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium Tank"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Heavy Tank"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tank Destroyer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SPGS"
                        });
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Characteristics", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.Tank", "Tank")
                        .WithOne("Characteristics")
                        .HasForeignKey("TP_Tankopedia_ASP.Models.Characteristics", "TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Tank", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.Nation", "Nation")
                        .WithMany("Tanks")
                        .HasForeignKey("NationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP_Tankopedia_ASP.Models.StrategicRole", "StrategicRole")
                        .WithMany("Tanks")
                        .HasForeignKey("StrategicRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP_Tankopedia_ASP.Models.TypeTank", "TypeTank")
                        .WithMany("Tanks")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nation");

                    b.Navigation("StrategicRole");

                    b.Navigation("TypeTank");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.TankModule", b =>
                {
                    b.HasOne("TP_Tankopedia_ASP.Models.Tank", "Tank")
                        .WithMany("TankModules")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Nation", b =>
                {
                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.StrategicRole", b =>
                {
                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.Tank", b =>
                {
                    b.Navigation("Characteristics")
                        .IsRequired();

                    b.Navigation("TankModules");
                });

            modelBuilder.Entity("TP_Tankopedia_ASP.Models.TypeTank", b =>
                {
                    b.Navigation("Tanks");
                });
#pragma warning restore 612, 618
        }
    }
}
